export const basicCourse1Array = [
  {
    number: "1",
    title: "What's your name?",
    series: "basicCourse1",
    character1: "a",
    character2: "b",
    numberOfLines: 5,
    line1Speaker: "a",
    line1: "Hello.",
    line2Speaker: "b",
    line2: "Hi.",
    line3Speaker: "a",
    line3: "What is your name?",
    line4Speaker: "b",
    line4: "My name is Sam. What's your name?",
    line5Speaker: "a",
    line5: "My name's Charlie.",
  },

  {
    number: "2",
    title: "What's your name?",
    series: "basicCourse1",
    character1: "a",
    character2: "b",
    numberOfLines: 5,
    line1Speaker: "a",
    line1: "Hello. This is part two.",
    line2Speaker: "b",
    line2: "Hi.",
    line3Speaker: "a",
    line3: "What is your name?",
    line4Speaker: "b",
    line4: "My name is Sam. What's your name?",
    line5Speaker: "a",
    line5: "My name's Charlie.",
  },
];
