export const basicEnglishOne = [
  {
    someinfo: "the info",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
  },
  {
    number: "1",
    title: "What's your name?",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 10,
    line1Speaker: "Marco",
    line1: "Hello.",
    line2Speaker: "Sally",
    line2: "Hi.",
    line3Speaker: "Marco",
    line3: "What's your name?",
    line4Speaker: "Sally",
    line4: "My name's Sam. What's your name?",
    line5Speaker: "Marco",
    line5: "My name's Charlie.",
    line6Speaker: "Sally",
    line6: "Hi Charlie. Nice to meet you.",
    line7Speaker: "Marco",
    line7: "Nice to meet you too.",
    line8Speaker: "Sally",
    line8: "What's your surname?",
    line9Speaker: "Marco",
    line9: "My surname is Rush. What about you?",
    line10Speaker: "Sally",
    line10: "My surname is Smith.",
  },

  {
    number: "2",
    title: "Are you Chinese?",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 20,
    line1Speaker: "Marco",
    line1: "What's your surname?",
    line2Speaker: "Sally",
    line2: "My surname is Lee.",
    line3Speaker: "Marco",
    line3: "Are you Chinese?",
    line4Speaker: "Sally",
    line4: "Yes. I am Chinese. Are you American?",
    line5Speaker: "Marco",
    line5: "Yes, I'm American.",
    line6Speaker: "Sally",
    line6: "Hi Charlie. Nice to meet you.",
    line7Speaker: "Marco",
    line7: "Nice to meet you too.",
    line8Speaker: "Sally",
    line8: "What's your surname?",
    line9Speaker: "Marco",
    line9: "My surname is Rush. What about you?",
    line10Speaker: "Sally",
    line10: "My surname is Smith.",
    line11Speaker: "Marco",
    line11: "What's your surname?",
    line12Speaker: "Sally",
    line12: "My surname is Lee.",
    line13Speaker: "Marco",
    line13:
      "Are you Chinese? I just want to know what happens if I write a lot of stuff. Just like in the Youtube videos I was trnaslating. I think for it to be truely engageing we will need the characters to say a lot in one line. What do you think?",
    line14Speaker: "Sally",
    line14: "CHANGE TO COLUMN?",
    line15Speaker: "Marco",
    line15: "Yes, I'm American.",
    line16Speaker: "Sally",
    line16: "Hi Charlie. Nice to meet you.",
    line17Speaker: "Marco",
    line17: "Nice to meet you too.",
    line18Speaker: "Sally",
    line18: "What's your surname?",
    line19Speaker: "Marco",
    line19: "My surname is Rush. What about you?",
    line20Speaker: "Sally",
    line20: "My surname is Smith.",
  },

  {
    number: "3",
    title: "Who is she?",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 8,
    line1Speaker: "Marco",
    line1: "Who is she?",
    line2Speaker: "Sally",
    line2: "That's Mary Lee.",
    line3Speaker: "Marco",
    line3: "Is she Korean?",
    line4Speaker: "Sally",
    line4: "No. She's Japanese.",
    line5Speaker: "Marco",
    line5: "Oh! Is she a teacher?",
    line6Speaker: "Sally",
    line6: "No. She's not a teacher. She's a student.",
    line7Speaker: "Marco",
    line7: "Who is the teacher?",
    line8Speaker: "Sally",
    line8: "He's the teacher!",
  },

  {
    number: "4",
    title: "Nice to meet you.",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 7,
    line1Speaker: "Marco",
    line1: "Hi, nice to meet you.",
    line2Speaker: "Sally",
    line2: "Nice to meet you too.",
    line3Speaker: "Marco",
    line3: "Are you a student or a teacher?",
    line4Speaker: "Sally",
    line4: "I'm a student.",
    line5Speaker: "Marco",
    line5: "Are you Germna or French?",
    line6Speaker: "Sally",
    line6: "I'm Spanish.",
    line7Speaker: "Marco",
    line7: "Oh.",
  },

  {
    number: "5",
    title: "Can you speak English?",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 4,
    line1Speaker: "Marco",
    line1: "Can you speak English?",
    line2Speaker: "Sally",
    line2: "No I can't, sorry.",
    line3Speaker: "Marco",
    line3: "What's your name?",
    line4Speaker: "Sally",
    line4: "Sorry, I don't understand.",
  },

  {
    number: "6",
    title: "Where's the toilet?",
    series: "basicEnglishOne",
    character1: "Marco",
    character1Age: "23",
    character1Nationality: "Brazil",
    character1Description: "Marco has gone to China to study!",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "22",
    character2Nationality: "USA",
    character2Description:
      "It will look silly if text is very long. We'll have to set limit? Portrait must be bigger than text...",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: 4,
    line1Speaker: "Marco",
    line1: "excuse me, where's the toilet?",
    line2Speaker: "Sally",
    line2: "It's over there.",
    line3Speaker: "Marco",
    line3: "Thank you.",
    line4Speaker: "Sally",
    line4: "It's okay.",
  },
];
