export const course3Array = [
  {
    number: "1",
    title: "What's your name?",
    series: "course3",
    character1: "a",
    character2: "b",
    numberOfLines: 5,
    line1Speaker: "a",
    line1: "Hello.",
    line2Speaker: "b",
    line2: "Hi.",
    line3Speaker: "a",
    line3: "What is your name?",
    line4Speaker: "b",
    line4: "My name is Sam. What's your name?",
    line5Speaker: "a",
    line5: "My name's Charlie.",
  },

  {
    number: "2",
    title: "What's your name?",
    series: "course3",
    character1: "a",
    character2: "b",
    numberOfLines: 5,
    line1Speaker: "a",
    line1: "Hello. This is part two.",
    line2Speaker: "b",
    line2: "Hi.",
    line3Speaker: "a",
    line3: "What is your name?",
    line4Speaker: "b",
    line4: "My name is Sam. What's your name?",
    line5Speaker: "a",
    line5: "My name's Charlie.",
  },

  {
    number: "3",
    title: "How old are you?",
    series: "course3",
    character1: "a",
    character2: "b",
    numberOfLines: 6,
    line1Speaker: "a",
    line1: "How old are you?",
    line2Speaker: "b",
    line2: "I can't remember, I'm too old.",
    line3Speaker: "a",
    line3: "Oh shit, you must be really old.",
    line4Speaker: "b",
    line4: "I was born in the 1980's!",
    line5Speaker: "a",
    line5: "Wow, does that mean you're a boomer?",
    line6Speaker: "b",
    line6:
      "Not quite, I'm not that old! OMG! You thought I was a boomer! Shit!",
  },
];
