export const kindleBook = [
  {
    someinfo: "info",
    level: "TBC",
    character1: "Marco",
    character1Age: "21",
    character1Nationality: "USA",
    character1Description: "Marco has gone to study abroad.",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Age: "22",
    character2Nationality: "France",
    character2Description: "Kate has gone to study abroad.",
    character2Image: require("../assets/images/sally.png"),
  },

  {
    number: "1",
    title: "How are you?",
    series: "kindleBook",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "10",
    intro: "",
    line1Speaker: "Marco",
    line1: "How's it going?",
    line2Speaker: "Kate",
    line2: "I'm okay thanks. How are you?",
    line3Speaker: "Marco",
    line3: "I'm fine.",
    line4Speaker: "Kate",
    line4: "That's nice to hear.",
    line5Speaker: "Marco",
    line5: "What have you been up to?",
    line6Speaker: "Kate",
    line6: "Nothing really, the usualy things.",
    line7Speaker: "Marco",
    line7: "Have you done anything interesting?",
    line8Speaker: "Kate",
    line8: "I went on holiday.",
    line9Speaker: "Marco",
    line9: "Where did you go?",
    line10Speaker: "Kate",
    line10: "I went to Japan.",
  },

  {
    number: "2",
    title: "What's your name?",
    series: "kindleBook",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "10",
    intro: "",
    line1Speaker: "Marco",
    line1: "What's your name?",
    line2Speaker: "Kate",
    line2: "My name's Kate.",
    line3Speaker: "Marco",
    line3: "What's your surname?",
    line4Speaker: "Kate",
    line4: "My surname is Smith.",
    line5Speaker: "Marco",
    line5: "Do you have a middle name?",
    line6Speaker: "Kate",
    line6: "I don't have a middle name.",
    line7Speaker: "Marco",
    line7: "What's your nickname?",
    line8Speaker: "Kate",
    line8: "My friends call me Kat.",
    line9Speaker: "Marco",
    line9: "What's your dog called?",
    line10Speaker: "Kate",
    line10: "I don't have a dog.",
  },

  {
    number: "3",
    title: "Where are you from?",
    series: "kindleBook",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "10",
    intro: "",
    line1Speaker: "Marco",
    line1: "Where are you from?",
    line2Speaker: "Kate",
    line2: "I'm from Germany.",
    line3Speaker: "Marco",
    line3: "Whereabouts in Germany?",
    line4Speaker: "Kate",
    line4: "I'm from Berlin.",
    line5Speaker: "Marco",
    line5: "Is it close to Denmark?",
    line6Speaker: "Kate",
    line6: "Not really, it's a few hours away.",
    line7Speaker: "Marco",
    line7: "Is your hometown a big place?",
    line8Speaker: "Kate",
    line8: "Not really, it's not that big.",
    line9Speaker: "Marco",
    line9: "How many people live there?",
    line10Speaker: "Kate",
    line10: "About thirty thousand.",
  },
];
