export const marcoStudiesAbroad = [
  {
    someinfo: "info",
    level: "Very Easy/Beginner",
    character1: "Marco",
    character1Age: "21",
    character1Nationality: "USA",
    character1Description: "Marco has gone to study abroad.",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Age: "22",
    character2Nationality: "France",
    character2Description: "Kate has gone to study abroad.",
    character2Image: require("../assets/images/sally.png"),
  },

  {
    number: "1",
    title: "What's your name?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Marco",
    line1: "Hello.",
    line2Speaker: "Kate",
    line2: "Hi.",
    line3Speaker: "Marco",
    line3: "What's your name?",
    line4Speaker: "Kate",
    line4: "My name's Kate. What's your name?",
    line5Speaker: "Marco",
    line5: "My name's Marco.",
  },

  {
    number: "2",
    title: "Are you American?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "8",
    intro: "",
    line1Speaker: "Marco",
    line1: "What's your surname?",
    line2Speaker: "Kate",
    line2: "My surname is Lee.",
    line3Speaker: "Marco",
    line3: "Are you Chinese?",
    line4Speaker: "Kate",
    line4: "No. I'm not. I'm French. Are you American?",
    line5Speaker: "Marco",
    line5: "Yes, I'm American.",
    line6Speaker: "Kate",
    line6: "How old are you?",
    line7Speaker: "Marco",
    line7: "I'm twenty one years old. How old are you?",
    line8Speaker: "Kate",
    line8: "I'm twenty two.",
  },

  {
    number: "3",
    title: "Do you have a girlfriend?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Kate",
    line1: "Are you married?",
    line2Speaker: "Marco",
    line2: "No, I'm not married.",
    line3Speaker: "Kate",
    line3: "Do you have a girlfriend?",
    line4Speaker: "Marco",
    line4: "No, I don't. I'm single. What about you? Do you have a boyfriend?",
    line5Speaker: "Kate",
    line5: "Yes, I do. I have a boyfriend.",
  },

  {
    number: "4",
    title: "Are you hungry?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "7",
    intro: "",
    line1Speaker: "Marco",
    line1: "Are you hungry?",
    line2Speaker: "Kate",
    line2: "Yes, I'm hungry.",
    line3Speaker: "Marco",
    line3: "Do you want to eat something?",
    line4Speaker: "Kate",
    line4: "Okay, let's eat together.",
    line5Speaker: "Marco",
    line5: "What do you want to eat?",
    line6Speaker: "Kate",
    line6: "I want to eat Chinese food. Where should we go to eat?",
    line7Speaker: "Marco",
    line7: "Let's go to a restaurant.",
  },

  {
    number: "5",
    title: "How are we going to get there?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Kate",
    line1: "Where's the restaurant?",
    line2Speaker: "Marco",
    line2: "It's not far, it's nearby.",
    line3Speaker: "Kate",
    line3: "How are we going to get there? Are we going by subway?",
    line4Speaker: "Marco",
    line4: "No, let's get the bus.",
    line5Speaker: "Kate",
    line5: "I don't like the bus. It's too crowded. Let's get a taxi.",
    line6Speaker: "Marco",
    line6: "Okay, let's find a taxi.",
  },

  {
    number: "6",
    title: "Where do you want to go?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    character3: "TaxiDriver",
    character3Image: require("../assets/images/taxiDriver.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Kate",
    line1: "Look, there's an empty taxi. Let's get in.",
    line2Speaker: "TaxiDriver",
    line2: "Taxi driver: Where do you want to go?",
    line3Speaker: "Marco",
    line3: "The Rose restaurant.",
    line4Speaker: "text",
    line4: "A short while later...",
    line5Speaker: "TaxiDriver",
    line5: "Taxi driver: Where is the restaurant?",
    line6Speaker: "Marco",
    line6: "Go straight ahead and then turn left.",
  },

  {
    number: "7",
    title: "What do you want to eat?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Marco",
    line1: "What do you want to eat?",
    line2Speaker: "Kate",
    line2: "Let's look at the menu.",
    line3Speaker: "Marco",
    line3: "Do you like spicy food?",
    line4Speaker: "Kate",
    line4: "No, I don't like spicy food.",
    line5Speaker: "text",
    line5: "Kate looks at the menu.",
    line6Speaker: "Kate",
    line6: "I want to eat this.",
  },

  {
    number: "8",
    title: "How much did it cost?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Marco",
    line1: "Is this your bag?",
    line2Speaker: "Kate",
    line2: "Yes, it's my bag.",
    line3Speaker: "Marco",
    line3: "How much did it cost?",
    line4Speaker: "Kate",
    line4: "It was three thousand dollars.",
    line5Speaker: "Marco",
    line5: "Wow, that's really expensive.",
    line6Speaker: "Kate",
    line6: "I know.",
  },

  {
    number: "9",
    title: "What would you like to drink?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "8",
    intro: "",
    line1Speaker: "Marco",
    line1: "Are you thirsty?",
    line2Speaker: "Kate",
    line2: "Yeah, I'm thirsty.",
    line3Speaker: "Marco",
    line3: "Shall we go to a coffee shop for a drink?",
    line4Speaker: "Kate",
    line4: "Okay. That sounds good.",
    line5Speaker: "Marco",
    line5: "What would you like to drink?",
    line6Speaker: "Kate",
    line6: "I want to an americano.",
    line7Speaker: "Marco",
    line7: "Small, medium or large?",
    line8Speaker: "Kate",
    line8: "Small please.",
  },

  {
    number: "10",
    title: "Do you have brothers or sisters?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Marco",
    line1: "Do you have brothers or sisters?",
    line2Speaker: "Kate",
    line2: "I have a younger sister.",
    line3Speaker: "Marco",
    line3: "What job does she do?",
    line4Speaker: "Kate",
    line4: "She works in a bank.",
    line5Speaker: "Marco",
    line5: "Where does she live?",
    line6Speaker: "Kate",
    line6: "She lives in Paris.",
  },

  {
    number: "11",
    title: "Do you have a pet?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Marco",
    line1: "Do you have a pet?",
    line2Speaker: "Kate",
    line2: "My family has a dog.",
    line3Speaker: "Marco",
    line3: "Is it a cute dog?",
    line4Speaker: "Kate",
    line4: "Yes, very cute.",
    line5Speaker: "Marco",
    line5: "How often do you walk your dog?",
    line6Speaker: "Kate",
    line6: "Every day.",
  },

  {
    number: "12",
    title: "Do you like sport?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "7",
    intro: "",
    line1Speaker: "Marco",
    line1: "Do you like sport?",
    line2Speaker: "Kate",
    line2: "Yeah, I do a lot of exercise.",
    line3Speaker: "Marco",
    line3: "What exercise do you do?",
    line4Speaker: "Kate",
    line4:
      "I like to play tennis. I also go to the gym a few times a week. What about you?",
    line5Speaker: "Marco",
    line5: "I like watching football, but I don't play it very often.",
    line6Speaker: "Kate",
    line6: "Can you swim?",
    line7Speaker: "Marco",
    line7: "Yes, I can swim.",
  },

  {
    number: "13",
    title: "What do you do in your free time?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Marco",
    line1: "What do you do in your free time?",
    line2Speaker: "Kate",
    line2: "I like to watch T.V.",
    line3Speaker: "Marco",
    line3: "What do you like to watch?",
    line4Speaker: "Kate",
    line4: "I like to watch soap operas, especially Korean soap operas.",
    line5Speaker: "Marco",
    line5: "Oh. I don’t usually watch soap operas. I prefer to watch the news.",
  },

  {
    number: "14",
    title: "Have you booked a hotel room?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "8",
    intro: "",
    line1Speaker: "Marco",
    line1: "The holiday is nearly here, do you have any plans?",
    line2Speaker: "Kate",
    line2: "I'm going traveling.",
    line3Speaker: "Marco",
    line3: "Who are you going with?",
    line4Speaker: "Kate",
    line4: "With my friend.",
    line5Speaker: "Marco",
    line5: "Have you booked a hotel?",
    line6Speaker: "Kate",
    line6: "Yeah, I've already booked a hotel.",
    line7Speaker: "Marco",
    line7: "Have you bought a plane ticket?",
    line8Speaker: "Kate",
    line8: "We're not going by plane. We'll get the train.",
  },

  {
    number: "15",
    title: "What shall we do now?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "8",
    intro: "",
    line1Speaker: "Marco",
    line1: "What shall we do now?",
    line2Speaker: "Kate",
    line2: "I want to go to the supermarket to buy some food.",
    line3Speaker: "Marco",
    line3: "What do you want to buy?",
    line4Speaker: "Kate",
    line4: "I want to buy some meat and some vegetables.",
    line5Speaker: "Marco",
    line5: "Just before we go, I need to use the toilet.",
    line6Speaker: "Kate",
    line6: "Okay, I'll wait for you here.",
    line7Speaker: "Marco",
    line7: "Where's the toilet?",
    line8Speaker: "Kate",
    line8: "It's over there.",
  },
];
