export const marcoInChina = [
  {
    someinfo: "info",
    character1: "Marco",
    character1Age: "25",
    character1Nationality: "France",
    character1Description: "Marco is a nice boy and wants a fun life",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Age: "25",
    character2Nationality: "Japan",
    character2Description: "She is also a nice girl and wants to have fun",
    character2Image: require("../assets/images/sallyImg.jpg"),
  },

  {
    number: "1",
    title: "Marco is on his bed feeling bored",
    series: "MarcoGoesToChina",
    character1: "Marco",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: "10",
    intro: "Marco is sitting on his bed feeling a little bit bored...",
    line1Speaker: "Marco",
    line1: "Sally, isn't there something more to life. I feel bored.",
    line2Speaker: "Sally",
    line2: "What more do you want? Do you want to go on an adventure?",
    line3Speaker: "Marco",
    line3:
      "Yes, I'm sat here looking at this world map and I want to get out of here. I want to go and see the world.",
    line4Speaker: "Sally",
    line4: "Where do you want to go?",
    line5Speaker: "Marco",
    line5: "I think I want to go to China.",
    line6Speaker: "Sally",
    line6: "Why China?",
    line7Speaker: "Marco",
    line7:
      "It's always interested me. I like the food and I want to see the great wall.",
    line8Speaker: "Sally",
    line8: "It will cost you a lot of money to go to China.",
    line9Speaker: "Marco",
    line9: "I know, but if I get a job and save up then maybe I can go",
    line10Speaker: "Sally",
    line10: "That sounds like a good idea. You can go during the holiday.",
  },

  {
    number: "2",
    title: "Marco is starting to make a plan",
    series: "MarcoGoesToChina",
    character1: "Marco",
    character1Image: require("../assets/images/9d5dda7604f544dca249fedf270f5bc8.jpg"),
    character2: "Sally",
    character2Image: require("../assets/images/sallyImg.jpg"),
    numberOfLines: "10",
    intro: "Marco is sitting on his bed feeling a little bit bored...",
    line1Speaker: "Marco",
    line1: "Sally, isn't there something more to life. I feel bored.",
    line2Speaker: "Sally",
    line2: "What more do you want? Do you want to go on an adventure?",
    line3Speaker: "Marco",
    line3:
      "Yes, I'm sat here looking at this world map and I want to get out of here. I want to go and see the world.",
    line4Speaker: "Sally",
    line4: "Where do you want to go?",
    line5Speaker: "Marco",
    line5: "I think I want to go to China.",
    line6Speaker: "Sally",
    line6: "Why China?",
    line7Speaker: "Marco",
    line7:
      "It's always interested me. I like the food and I want to see the great wall.",
    line8Speaker: "Sally",
    line8: "It will cost you a lot of money to go to China.",
    line9Speaker: "Marco",
    line9: "I know, but if I get a job and save up then maybe I can go",
    line10Speaker: "Sally",
    line10: "That sounds like a good idea. You can go during the holiday.",
  },
];
