export const marcoStudiesAbroad = [
  {
    someinfo: "info",
    level: "Easy/Beginner",
    character1: "Marco",
    character1Age: "21",
    character1Nationality: "USA",
    character1Description: "Marco has gone to study abroad.",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Age: "22",
    character2Nationality: "France",
    character2Description: "Kate has gone to study abroad.",
    character2Image: require("../assets/images/sally.png"),
  },

  {
    number: "1",
    title: "What's your name?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "7",
    intro: "",
    line1Speaker: "Marco",
    line1: "Hello.",
    line2Speaker: "Kate",
    line2: "Hi.",
    line3Speaker: "Marco",
    line3: "What's your name?",
    line4Speaker: "Kate",
    line4: "My name's Kate. What's your name?",
    line5Speaker: "Marco",
    line5: "My name's Marco.",
    line6Speaker: "Kate",
    line6: "Nice to meet you Marco.",
    line7Speaker: "Marco",
    line7: "Nice to meet you too.",
  },

  {
    number: "2",
    title: "Are you American?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Marco",
    line1: "What's your surname?",
    line2Speaker: "Kate",
    line2: "My surname is Lee.",
    line3Speaker: "Marco",
    line3: "Are you Chinese?",
    line4Speaker: "Kate",
    line4: "No. I'm not. I'm French. Are you American?",
    line5Speaker: "Marco",
    line5: "Yes, I'm American.",
  },

  {
    number: "3",
    title: "How old are you?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "3",
    intro: "",
    line1Speaker: "Marco",
    line1: "How old are you?",
    line2Speaker: "Kate",
    line2: "I'm twenty one years old. How old is Kate?",
    line3Speaker: "Marco",
    line3: "I don't know. I think she's twenty two.",
  },

  {
    number: "4",
    title: "Do you have a girlfriend?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Kate",
    line1: "Are you married?",
    line2Speaker: "Marco",
    line2: "No, I'm not married.",
    line3Speaker: "Kate",
    line3: "Do you have a girlfriend?",
    line4Speaker: "Marco",
    line4: "No, I don't. I'm single. Do you have a boyfriend?",
    line5Speaker: "Kate",
    line5: "Yes, I do. I have a boyfriend.",
  },

  {
    number: "5",
    title: "Are you hungry?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "7",
    intro: "",
    line1Speaker: "Marco",
    line1: "Are you hungry?",
    line2Speaker: "Kate",
    line2: "Yes, I'm hungry.",
    line3Speaker: "Marco",
    line3: "Do you want to eat something?",
    line4Speaker: "Kate",
    line4: "Okay, let's eat together.",
    line5Speaker: "Marco",
    line5: "What do you want to eat?",
    line6Speaker: "Kate",
    line6: "I want to eat Chinese food. Where should we go to eat?",
    line7Speaker: "Marco",
    line7: "Let's go to a restaurant.",
  },

  {
    number: "6",
    title: "Are we going by subway?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "5",
    intro: "",
    line1Speaker: "Kate",
    line1: "Where's the restaurant?",
    line2Speaker: "Marco",
    line2: "Not far, it's nearby.",
    line3Speaker: "Kate",
    line3: "Are we going by subway?",
    line4Speaker: "Marco",
    line4: "No, let's get the bus.",
    line5Speaker: "Kate",
    line5: "The bus is too crowded. Let's get a taxi.",
  },

  {
    number: "7",
    title: "Where do you want to go?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    character3: "TaxiDriver",
    character3Image: require("../assets/images/taxiDriver.png"),
    numberOfLines: "4",
    intro: "",
    line1Speaker: "Kate",
    line1: "Look, there's an empty taxi. Let's get in.",
    line2Speaker: "TaxiDriver",
    line2: "Taxi driver: Where do you want to go?",
    line3Speaker: "Marco",
    line3: "The Rose restaurant.",
    line4Speaker: "TaxiDriver",
    line4: "Taxi driver: Okay, let's go.",
  },

  {
    number: "8",
    title: "Where do you want to go?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    character3: "TaxiDriver",
    character3Image: require("../assets/images/taxiDriver.png"),
    numberOfLines: "4",
    intro: "",
    line1Speaker: "TaxiDriver",
    line1: "Taxi driver: Where is the rose restaurant? It is here?",
    line2Speaker: "Marco",
    line2: "No, not here, go straight ahead.",
    line3Speaker: "TaxiDriver",
    line3: "Taxi driver: Oh, straight ahead?",
    line4Speaker: "Marco",
    line4: "Yeah, straight ahead and then turn left.",
    line5Speaker: "TaxiDriver",
    line5: "Taxi driver: Here?",
    line6Speaker: "Marco",
    line6: "Yeah, this is it.",
  },

  {
    number: "9",
    title: "What do you want to eat?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "4",
    intro: "",
    line1Speaker: "Marco",
    line1: "What do you want to eat?",
    line2Speaker: "Kate",
    line2: "Let's look at the menu.",
    line3Speaker: "Marco",
    line3: "Do you like spicy food?",
    line4Speaker: "Kate",
    line4: "No, I don't like spicy food. I want to eat this.",
  },

  {
    number: "10",
    title: "What do you think of this food?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "4",
    intro: "",
    line1Speaker: "Marco",
    line1: "What do you want to eat?",
    line2Speaker: "Kate",
    line2: "Let's look at the menu.",
    line3Speaker: "Marco",
    line3: "Do you like spicy food?",
    line4Speaker: "Kate",
    line4: "No, I don't like spicy food. I want to eat this.",
  },

  {
    number: "11",
    title: "How much was this?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "6",
    intro: "",
    line1Speaker: "Marco",
    line1: "Is this your bag?",
    line2Speaker: "Kate",
    line2: "Yes, it's my bag.",
    line3Speaker: "Marco",
    line3: "How much did it cost?",
    line4Speaker: "Kate",
    line4: "It was three thousand dollars.",
    line5Speaker: "Marco",
    line5: "Wow, that's really expensive.",
    line6Speaker: "Kate",
    line6: "I know.",
  },

  {
    number: "12",
    title: "Where's the toilet?",
    series: "marcoStudiesAbroad",
    character1: "Marco",
    character1Image: require("../assets/images/marco.png"),
    character2: "Kate",
    character2Image: require("../assets/images/sally.png"),
    numberOfLines: "2",
    intro: "",
    line1Speaker: "Marco",
    line1: "Where's the toilet?",
    line2Speaker: "Kate",
    line2: "It's over there.",
  },

  // you are on to number 26 in the book
];
