export const arrayOfStories = [
  {
    storyNumber: "1",
    storyTitle: "A nice story",
    character1: "Jim",
    character2: "Sarah",
    character3: "Tycus",
    numberOfLines: 6,
    line1Speaker: "Jim",
    line1: "Hello there, my name is Jim Raynor.",
    line2Speaker: "Sarah",
    line2: "Hi Jimmy, it's me Kerrigan.",
    line3Speaker: "Jim",
    line3:
      "Nice to meet you, isn't it really cool that this is coming from the database? Sorry, not the database, the module, just as good, and cheaper!",
    line4Speaker: "Sarah",
    line4:
      "Yes it is Jim, it's amazing. Now I'm just going to talk a little bit too much because I want to see what happens if we needs two lines... Is that enough? Oh wow, that's great, works well doesn't it Jim?",
    line5Speaker: "Jim",
    line5:
      "Yes it does, do you think you can write 6000 words everyday just like lutx? Is it an accident? Remind me to make this one better so it can scale! Also, let's get some AI art in here to make it look really cool!",
    line6Speaker: "Tycus",
    line6: "Can you two stop talking, we have work to do!",
  },

  {
    storyNumber: "2",
    storyTitle: "a second story",
    character1: "bob",
    character2: "sally",
    character3: "joe",
    numberOfLines: 6,
    line1Speaker: "bob",
    line1: "hi there, how are you?",
    line2Speaker: "sally",
    line2: "I'm good, and you?",
    line3Speaker: "bob",
    line3: "I'm great, better now I've met you",
    line4Speaker: "sally",
    line4: "wow bob, you have a sweet tongue",
    line5Speaker: "bob",
    line5: "I know sally, I'm a ladies man.",
    line6Speaker: "joe",
    line6: "omg, this is so cringe!",
  },

  {
    storyNumber: "3",
    storyTitle: "a third and longer story",
    character1: "bob",
    character2: "sally",
    character3: "joe",
    numberOfLines: 8,
    line1Speaker: "bob",
    line1: "hi there, how are you?",
    line2Speaker: "sally",
    line2: "I'm good, and you?",
    line3Speaker: "bob",
    line3: "I'm great, better now I've met you",
    line4Speaker: "sally",
    line4: "wow bob, you have a sweet tongue",
    line5Speaker: "bob",
    line5: "I know sally, I'm a ladies man.",
    line6Speaker: "joe",
    line6: "omg, this is so cringe!",
    line7Speaker: "joe",
    line7: "omg, this is so line 7!",
    line8Speaker: "joe",
    line8: "omg, this is so line 8!",
  },

  {
    storyNumber: "4",
    storyTitle: "a fourth  and shorter story",
    character1: "bob",
    character2: "sally",
    character3: "joe",
    numberOfLines: 4,
    line1Speaker: "bob",
    line1: "hi there, how are you?",
    line2Speaker: "sally",
    line2: "I'm good, and you?",
    line3Speaker: "bob",
    line3: "I'm great, better now I've met you",
    line4Speaker: "sally",
    line4:
      "wow bob, you have a sweet tongue, but I want to finish on line 4 thanks",
  },
];
